spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema.sql
    url: jdbc:h2:mem:Mydb
    username: root
    password: 1234
  h2:
    console:
      enabled: false
  jmx:
    enabled: false

mybatis-plus:
  global-config:
    banner: false

logging:
  level:
    com.lqc: error
    com.zaxxer: error

